---
- name: single host commands
  hosts: subspace-dx1
  gather_facts: false
  connection: local


  tasks:
    - name: run command
      nclu:
        commands:
            - show interface
      register: print_output
    - debug: var=print_output 
