---
- name: egss qos test all admins
  hosts: menaadmins,!f1060-jed-stc-admin1
  gather_facts: false

  tasks:

    - name: Run egg qos admin server test
      command: /home/netmeter/iprelay/eggsqos {{item}}
      with_items:
          - '143.131.160.4'
#          - 'ping-exporter-2'
#          - 'ping-exporter-3'
#          - 'ping-exporter-4'
#          - 'ping-exporter-5'
#          - 'ping-exporter-6'
      register: output
#    - name: Start Node Exporter
#      systemd:
#        name: node_exporter
#        state: started

#    - name: Start ping exporter service
#      systemd:
#        name: '{{item}}'
#        state: started
#      with_items:
#          - 'ping-exporter-1'
#          - 'ping-exporter-2'
#          - 'ping-exporter-3'
#          - 'ping-exporter-4'
#          - 'ping-exporter-5'
#          - 'ping-exporter-6'
