---
- name: fujirrah
  hosts: subspace-fuj
  gather_facts: false
  
  tasks:
  - name: copy new daemon and backup the current
    copy: 
      src:  '{{item}}'
      dest: /usr/src/gobgp/
      mode: a+x
      backup: yes
      remote_src: yes
    with_items:
        - /root/gobgp_new/gobgp
        - /root/gobgp_new/gobgpd
    tags:
    - copy
    register: print_output
  - debug: var=print_output
  
  - name: copy new daemon and backup the current
    copy: 
      src:  '{{item}}'
      dest: /usr/local/bin
      mode: a+x
      backup: yes
      remote_src: yes
      with_items:
          - /root/gobgp_new/gobgp
          - /root/gobgp_new/gobgpd
    tags:
    - copy
    register: print_output
  - debug: var=print_output
  
  - name: restart gobgp daemon
    systemd:
      name: '{{item}}'
      state: restarted
    with_items:
        - gobgpd.ipt
        - gobgpd.peering
    tags:
    - restart
    register: print_output
  - debug: var=print_output
  
  - name: reannounce overlays and site local
    shell: '{{item}}'
    with_items:
        - gobgp g r a -a ipv4 143.131.160.0/24 community 0:6939,0:32590,0:3356
        - gobgp g r a -a ipv4 143.131.161.0/24 community 0:6939,0:32590,0:3356
        - gobgp g r a -a ipv4 151.106.166.0/24
        - gobgp g r a -a ipv4 151.106.167.0/24
        - gobgp g r a -a ipv4 170.52.0.0/24
        - gobgp g r a -a ipv4 170.52.1.0/24
        - gobgp g r a -a ipv4 170.52.2.0/24
        - gobgp -p 50059 g r a -a ipv4 143.131.160.0/24
        - gobgp -p 50059 g r a -a ipv4 143.131.161.0/24
        - gobgp -p 50059 g r a -a ipv4 151.106.166.0/24
        - gobgp -p 50059 g r a -a ipv4 151.106.167.0/24
        - gobgp -p 50059 g r a -a ipv4 170.52.0.0/24
        - gobgp -p 50059 g r a -a ipv4 170.52.1.0/24
        - gobgp -p 50059 g r a -a ipv4 170.52.2.0/24
    tags:
    - announce
    register: print_output
  - debug: var=print_output

  - name: verify announcements fuj
    shell: '{{item}}'
    with_items:
        - gobgp n 195.229.29.149 adj-out 
        - gobgp -p 50059 n 72.14.198.132 adj-out
    tags:
    - verify
    register: print_output
  - debug: var=print_output
